apiVersion: v2
name: scanfarmdeps
description: Example Helm chart for Scan Farm dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
- name: minio
  version: 11.10.24
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  version: 12.12.10
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 17.3.17
  repository: https://charts.bitnami.com/bitnami