apiVersion: v2
name: scanfarmdeps
description: Example Helm chart for Scan Farm dependencies
type: application
version: 0.2.0
appVersion: "1.1.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
- name: minio
  version: 17.0.16
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  version: 16.6.7
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 21.0.0
  repository: https://charts.bitnami.com/bitnami