{{- if (and .Values.tls.certManager.enabled .Values.features.to) -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.to.tlsSecret }}
spec:
  isCA: false
  commonName: {{ include "srm-to.fullname" . }}
  secretName: {{ .Values.to.tlsSecret }}
  duration: {{ .Values.tls.certManager.duration | quote }}
  renewBefore: {{ .Values.tls.certManager.renewBefore | quote }}
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "srm-to.fullname" . }}
    - {{ include "srm-to.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "srm-to.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  subject:
    organizations:
      - cert-manager
    countries:
      - US
  issuerRef:
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ .Values.tls.certManager.issuerRef.kind }}
    group: cert-manager.io
{{- end -}}