{{- if .Values.tls.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.web.tlsSecret }}
spec:
  isCA: false
  commonName: {{ include "srm-web.fullname" . }}
  secretName: {{ .Values.web.tlsSecret }}
  duration: {{ .Values.tls.certManager.duration | quote }}
  renewBefore: {{ .Values.tls.certManager.renewBefore | quote }}
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "srm-web.fullname" . }}
    - {{ include "srm-web.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "srm-web.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  subject:
    organizations:
      - cert-manager
    countries:
      - US
  issuerRef:
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ .Values.tls.certManager.issuerRef.kind }}
    group: cert-manager.io
{{- end -}}