{{- if .Values.features.scanfarm -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "srm-sf.svc-cronjob" . | quote }}
  labels:
    {{- include "srm-sf.svc-job-labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.web.scanfarm.key.regenSchedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "srm-sf.svc-job-labels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "srm-web.serviceAccountName" . | quote }}
          securityContext:
          {{- toYaml .Values.web.podSecurityContext | nindent 12 }}
          {{- if .Values.web.nodeSelectors }}
          nodeSelector:
          {{- toYaml .Values.web.nodeSelectors | trim | nindent 12 }}
          {{- end }}
          {{- if .Values.web.tolerations }}
          tolerations:
          {{- toYaml .Values.web.tolerations | trim | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
          - name: configuration-job
            image: "{{ .Values.web.image.registry }}/{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
            securityContext:
            {{- toYaml .Values.web.securityContext | nindent 14 }}
            command:
              - /bin/bash
              - -c
              - |
{{ include "srm-web.key-job" . | indent 16 }}
            volumeMounts:
            - name: web-secret
              mountPath: {{ include "srm-web.admin.password.path" . }}
              subPath: {{ include "srm-web.admin.password.filename" . }}
            {{- if .Values.web.caConfigMap }}
            - name: web-ca
              mountPath: /certs/ca.crt
              subPath: ca.crt
            {{- end }}
          volumes:
          - name: web-secret
            secret:
              secretName: {{ include "srm-web.web.secret" . | quote }}
          {{- if .Values.web.caConfigMap }}
          - name: web-ca
            configMap:
              name: {{ .Values.web.caConfigMap | quote }}
              items:
              - key: ca.crt
                path: ca.crt
          {{- end }}
{{- end -}}