{{- if .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "srm-web.serviceAccountName" . }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.web.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
