{{- if .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "srm-web.serviceAccountName" . }}
  labels:
    {{- include "srm-web.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.web.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.web.database.rdsAuth.enabled }}
    eks.amazonaws.com/role-arn: {{ required "You must specify an AWS IAM Role ARN (.Values.web.database.rdsAuth.iamRoleArn) when creating a service account with RDS auth enabled (.Values.web.database.rdsAuth.enabled)" .Values.web.database.rdsAuth.iamRoleArn | quote }}
  {{- end }}
{{- end }}
