{{- if .Values.features.to -}}
{{- $saName := (include "srm-to.serviceAccountName" .) | quote -}}
{{- $rName := (include "srm-to.rolename" .) | quote -}}
{{- $rbName := (include "srm-to.rolebindingname" .) | quote -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $rName }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["bind"]
  resourceNames: [{{ include "srm-to.workflow.role.name" . | quote }}]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "srm-to.workflow.role.name" . | quote }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rbName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "srm-to.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rName }}
subjects:
- name: {{ $saName }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}

{{- end -}}