class Step : GuidedSetupStep {

	[Config] $config

	# the previous config file is an optional reference to a config.json
	# file that was previously generated by a Helm Prep Wizard instance.
	[Config] $previousConfig

	Step([string] $name, 
		[Config] $config,
		[string] $title,
		[string] $message,
		[string] $prompt) : base($name, $title, $message, $prompt) {

		$this.config = $config
	}

	[string]GetMessageFooter() {

		if ($null -eq $this.previousConfig) {
			return ""
		}

		$configFields = $this.GetType().GetCustomAttributes($false) | Select-Object -ExpandProperty 'values' -First 1
		if ($null -eq $configFields) {
			return ""
		}

		$configFieldValues = $configFields | ForEach-Object {
			"`n  $_`: $($this.previousConfig.$_)"
		}
		return ("---`nPrevious Config:" + [string]::join("", $configFieldValues) + "`n---")
	}
}
